export const countries = {
    france: { name:"France", pop:20000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["belgium", "germany", "italy", "spain", "switzerland", "uk"], world:"earth" },
    germany: { name:"Germany", pop:20000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["austria", "czech", "denmark", "france", "italy", "netherlands", "poland", "switzerland"], world:"earth" },
    spain: { name:"Spain", pop:18000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france", "italy", "portugal"], world:"earth" },
    italy: { name:"Italy", pop:19000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["austria", "croatia", "france", "germany", "spain", "switzerland"], world:"earth" },
    poland: { name:"Poland", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany", "lithuania", "moldova", "romania", "slovakia", "ukraine"], world:"earth" },
    ukraine: { name:"Ukraine", pop:21000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["bulgaria", "moldova", "poland", "romania", "russia", "serbia", "slovakia"], world:"earth" },
    uk: { name:"United Kingdom", pop:22000, level:1, owner:"ai", military:1, airports:2, trains:1, adjacent:["belgium", "denmark", "finland", "france", "ireland", "netherlands", "sweden"], world:"earth" },
    russia: { name:"Russia", pop:144000, level:1, owner:"ai", military:5, airports:3, trains:3, adjacent:["bulgaria", "china", "estonia", "finland", "kazakhstan", "latvia", "mongolia", "north_korea", "ukraine"], world:"earth" },
    sweden: { name:"Sweden", pop:15000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["denmark", "finland", "ireland", "norway", "uk"], world:"earth" },
    norway: { name:"Norway", pop:14000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["finland", "ireland", "sweden"], world:"earth" },
    finland: { name:"Finland", pop:5500, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["denmark", "norway", "russia", "sweden", "uk"], world:"earth" },
    denmark: { name:"Denmark", pop:5800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["belgium", "finland", "germany", "sweden", "uk"], world:"earth" },
    netherlands: { name:"Netherlands", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:2, adjacent:["belgium", "germany", "ireland", "portugal", "uk"], world:"earth" },
    belgium: { name:"Belgium", pop:11000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["denmark", "france", "netherlands", "uk"], world:"earth" },
    switzerland: { name:"Switzerland", pop:8000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["austria", "czech", "france", "germany", "italy"], world:"earth" },
    austria: { name:"Austria", pop:9000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany", "hungary", "italy", "slovakia", "switzerland"], world:"earth" },
    czech: { name:"Czechia", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany", "switzerland"], world:"earth" },
    slovakia: { name:"Slovakia", pop:5000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["austria", "hungary", "poland", "romania", "ukraine"], world:"earth" },
    hungary: { name:"Hungary", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["austria", "croatia", "romania", "serbia", "slovakia"], world:"earth" },
    romania: { name:"Romania", pop:19000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bulgaria", "hungary", "moldova", "poland", "serbia", "slovakia", "ukraine"], world:"earth" },
    bulgaria: { name:"Bulgaria", pop:7000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bosnia", "greece", "north_macedonia", "romania", "russia", "serbia", "turkey", "ukraine"], world:"earth" },
    serbia: { name:"Serbia", pop:8000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bosnia", "bulgaria", "croatia", "hungary", "north_macedonia", "romania", "ukraine"], world:"earth" },
    croatia: { name:"Croatia", pop:4000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bosnia", "hungary", "italy", "serbia"], world:"earth" },
    bosnia: { name:"Bosnia & Herz.", pop:3000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bulgaria", "croatia", "serbia"], world:"earth" },
    albania: { name:"Albania", pop:3000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["estonia", "greece", "latvia", "north_macedonia"], world:"earth" },
    north_macedonia: { name:"North Macedonia", pop:2000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["albania", "bulgaria", "greece", "latvia", "lithuania", "serbia"], world:"earth" },
    greece: { name:"Greece", pop:16000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["albania", "bulgaria", "estonia", "north_macedonia", "turkey"], world:"earth" },
    portugal: { name:"Portugal", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["ireland", "netherlands", "spain"], world:"earth" },
    ireland: { name:"Ireland", pop:5000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["netherlands", "norway", "portugal", "sweden", "uk"], world:"earth" },
    moldova: { name:"Moldova", pop:2600, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["poland", "romania", "ukraine"], world:"earth" },
    estonia: { name:"Estonia", pop:1300, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["albania", "greece", "latvia", "russia"], world:"earth" },
    latvia: { name:"Latvia", pop:1900, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["albania", "estonia", "lithuania", "north_macedonia", "russia"], world:"earth" },
    lithuania: { name:"Lithuania", pop:2700, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["latvia", "north_macedonia", "poland"], world:"earth" },
    china: { name:"China", pop:1400000, level:1, owner:"ai", military:10, airports:5, trains:5, adjacent:["afghanistan", "india", "kazakhstan", "mongolia", "north_korea", "pakistan", "russia", "south_korea", "vietnam"], world:"earth" },
    india: { name:"India", pop:1380000, level:1, owner:"ai", military:10, airports:5, trains:5, adjacent:["bangladesh", "china", "pakistan", "vietnam"], world:"earth" },
    japan: { name:"Japan", pop:125000, level:1, owner:"ai", military:3, airports:3, trains:3, adjacent:["north_korea", "philippines", "south_korea"], world:"earth" },
    south_korea: { name:"South Korea", pop:51000, level:1, owner:"ai", military:2, airports:2, trains:2, adjacent:["china", "japan", "mongolia", "north_korea", "philippines", "vietnam"], world:"earth" },
    north_korea: { name:"North Korea", pop:25000, level:1, owner:"ai", military:3, airports:1, trains:1, adjacent:["china", "japan", "mongolia", "russia", "south_korea"], world:"earth" },
    vietnam: { name:"Vietnam", pop:97000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["bangladesh", "china", "india", "philippines", "south_korea", "thailand"], world:"earth" },
    thailand: { name:"Thailand", pop:69000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["bangladesh", "indonesia", "philippines", "vietnam"], world:"earth" },
    indonesia: { name:"Indonesia", pop:273000, level:1, owner:"ai", military:5, airports:4, trains:3, adjacent:["australia", "papua_new_guinea", "philippines", "thailand"], world:"earth" },
    philippines: { name:"Philippines", pop:109000, level:1, owner:"ai", military:2, airports:2, trains:1, adjacent:["indonesia", "japan", "south_korea", "thailand", "vietnam"], world:"earth" },
    pakistan: { name:"Pakistan", pop:220000, level:1, owner:"ai", military:4, airports:2, trains:2, adjacent:["afghanistan", "china", "india", "iran", "saudi_arabia"], world:"earth" },
    bangladesh: { name:"Bangladesh", pop:164000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["india", "thailand", "vietnam"], world:"earth" },
    iran: { name:"Iran", pop:83000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["afghanistan", "iraq", "pakistan", "saudi_arabia", "turkey"], world:"earth" },
    iraq: { name:"Iraq", pop:40000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["iran", "saudi_arabia", "syria", "turkey"], world:"earth" },
    saudi_arabia: { name:"Saudi Arabia", pop:34000, level:1, owner:"ai", military:3, airports:2, trains:1, adjacent:["afghanistan", "iran", "iraq", "israel", "pakistan", "syria"], world:"earth" },
    turkey: { name:"Turkey", pop:84000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["bulgaria", "greece", "iran", "iraq", "israel", "syria"], world:"earth" },
    israel: { name:"Israel", pop:9000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["afghanistan", "egypt", "saudi_arabia", "syria", "turkey"], world:"earth" },
    syria: { name:"Syria", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["iraq", "israel", "saudi_arabia", "turkey"], world:"earth" },
    kazakhstan: { name:"Kazakhstan", pop:19000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["china", "mongolia", "russia"], world:"earth" },
    mongolia: { name:"Mongolia", pop:3300, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["china", "kazakhstan", "north_korea", "russia", "south_korea"], world:"earth" },
    afghanistan: { name:"Afghanistan", pop:38000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["china", "iran", "israel", "pakistan", "saudi_arabia"], world:"earth" },
    usa: { name:"United States", pop:331000, level:1, owner:"ai", military:10, airports:8, trains:8, adjacent:["canada", "cuba", "mexico"], world:"earth" },
    canada: { name:"Canada", pop:38000, level:1, owner:"ai", military:2, airports:3, trains:3, adjacent:["mexico", "usa"], world:"earth" },
    mexico: { name:"Mexico", pop:128000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["canada", "cuba", "usa"], world:"earth" },
    brazil: { name:"Brazil", pop:213000, level:1, owner:"ai", military:4, airports:3, trains:3, adjacent:["argentina", "colombia", "peru", "venezuela"], world:"earth" },
    argentina: { name:"Argentina", pop:45000, level:1, owner:"ai", military:2, airports:2, trains:2, adjacent:["brazil", "chile", "peru"], world:"earth" },
    colombia: { name:"Colombia", pop:50000, level:1, owner:"ai", military:2, airports:2, trains:1, adjacent:["brazil", "peru", "venezuela"], world:"earth" },
    peru: { name:"Peru", pop:33000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["argentina", "brazil", "chile", "colombia", "venezuela"], world:"earth" },
    chile: { name:"Chile", pop:19000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["argentina", "peru"], world:"earth" },
    venezuela: { name:"Venezuela", pop:28000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["brazil", "colombia", "peru"], world:"earth" },
    cuba: { name:"Cuba", pop:11000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["mexico", "usa"], world:"earth" },
    egypt: { name:"Egypt", pop:100000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["ethiopia", "israel", "libya", "sudan"], world:"earth" },
    nigeria: { name:"Nigeria", pop:206000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["algeria", "cameroon", "ghana", "libya", "sudan"], world:"earth" },
    south_africa: { name:"South Africa", pop:59000, level:1, owner:"ai", military:2, airports:2, trains:2, adjacent:["angola"], world:"earth" },
    kenya: { name:"Kenya", pop:53000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["drc", "ethiopia", "madagascar", "tanzania"], world:"earth" },
    ethiopia: { name:"Ethiopia", pop:115000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["egypt", "kenya", "sudan"], world:"earth" },
    drc: { name:"DR Congo", pop:89000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["angola", "cameroon", "kenya", "sudan", "tanzania"], world:"earth" },
    sudan: { name:"Sudan", pop:43000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["drc", "egypt", "ethiopia", "libya", "nigeria"], world:"earth" },
    libya: { name:"Libya", pop:6800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["algeria", "egypt", "nigeria", "sudan"], world:"earth" },
    algeria: { name:"Algeria", pop:44000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["ghana", "libya", "morocco", "nigeria"], world:"earth" },
    morocco: { name:"Morocco", pop:37000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["algeria", "ghana"], world:"earth" },
    ghana: { name:"Ghana", pop:31000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["algeria", "cameroon", "morocco", "nigeria"], world:"earth" },
    cameroon: { name:"Cameroon", pop:26000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["angola", "drc", "ghana", "nigeria"], world:"earth" },
    tanzania: { name:"Tanzania", pop:60000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["drc", "kenya", "madagascar"], world:"earth" },
    angola: { name:"Angola", pop:32000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["cameroon", "drc", "south_africa"], world:"earth" },
    madagascar: { name:"Madagascar", pop:28000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["kenya", "tanzania"], world:"earth" },
    australia: { name:"Australia", pop:25000, level:1, owner:"ai", military:2, airports:3, trains:2, adjacent:["indonesia", "new_zealand", "papua_new_guinea"], world:"earth" },
    new_zealand: { name:"New Zealand", pop:5000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["australia"], world:"earth" },
    papua_new_guinea: { name:"Papua New Guinea", pop:9000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["australia", "indonesia"], world:"earth" },
};
