export const countries = {
    // EUROPE
    france: { name:"France", pop:20000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["spain","germany","italy","belgium","switzerland","luxembourg","andorra"], world:"earth" },
    germany: { name:"Germany", pop:20000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","poland","czech","austria","switzerland","belgium","netherlands","denmark"], world:"earth" },
    spain: { name:"Spain", pop:18000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","portugal","andorra"], world:"earth" },
    italy: { name:"Italy", pop:19000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","austria","switzerland","slovenia","croatia","san_marino","vatican"], world:"earth" },
    poland: { name:"Poland", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany","czech","slovakia","ukraine","lithuania","belarus","kaliningrad"], world:"earth" },
    ukraine: { name:"Ukraine", pop:21000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["poland","slovakia","hungary","romania","moldova","belarus","russia"], world:"earth" },
    uk: { name:"United Kingdom", pop:22000, level:1, owner:"ai", military:1, airports:2, trains:1, adjacent:["france","ireland"], world:"earth" },
    russia: { name:"Russia", pop:144000, level:1, owner:"ai", military:5, airports:3, trains:3, adjacent:["ukraine","belarus","finland","norway","estonia","latvia","lithuania","poland","georgia","azerbaijan","kazakhstan","china","mongolia","north_korea"], world:"earth" },
    sweden: { name:"Sweden", pop:15000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["norway","finland","denmark"], world:"earth" },
    norway: { name:"Norway", pop:14000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["sweden","finland","russia"], world:"earth" },
    finland: { name:"Finland", pop:5500, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["sweden","norway","russia"], world:"earth" },
    denmark: { name:"Denmark", pop:5800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany","sweden"], world:"earth" },
    netherlands: { name:"Netherlands", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:2, adjacent:["belgium","germany"], world:"earth" },
    belgium: { name:"Belgium", pop:11000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","netherlands","germany","luxembourg"], world:"earth" },
    switzerland: { name:"Switzerland", pop:8000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","germany","austria","italy","liechtenstein"], world:"earth" },
    austria: { name:"Austria", pop:9000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany","czech","slovakia","hungary","slovenia","italy","switzerland","liechtenstein"], world:"earth" },
    czech: { name:"Czechia", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany","poland","slovakia","austria"], world:"earth" },
    slovakia: { name:"Slovakia", pop:5000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["czech","poland","ukraine","hungary","austria"], world:"earth" },
    hungary: { name:"Hungary", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["slovakia","ukraine","romania","serbia","croatia","slovenia","austria"], world:"earth" },
    romania: { name:"Romania", pop:19000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["hungary","ukraine","moldova","bulgaria","serbia"], world:"earth" },
    bulgaria: { name:"Bulgaria", pop:7000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["romania","serbia","north_macedonia","greece","turkey"], world:"earth" },
    serbia: { name:"Serbia", pop:8000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["hungary","romania","bulgaria","north_macedonia","kosovo","montenegro","bosnia","croatia"], world:"earth" },
    croatia: { name:"Croatia", pop:4000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["slovenia","hungary","serbia","bosnia"], world:"earth" },
    bosnia: { name:"Bosnia & Herz.", pop:3000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["croatia","serbia","montenegro"], world:"earth" },
    albania: { name:"Albania", pop:3000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["montenegro","kosovo","north_macedonia","greece"], world:"earth" },
    north_macedonia: { name:"North Macedonia", pop:2000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["kosovo","serbia","bulgaria","greece","albania"], world:"earth" },
    greece: { name:"Greece", pop:16000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["albania","north_macedonia","bulgaria","turkey"], world:"earth" },
    portugal: { name:"Portugal", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["spain"], world:"earth" },
    ireland: { name:"Ireland", pop:5000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["uk"], world:"earth" },
    moldova: { name:"Moldova", pop:2600, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["romania","ukraine"], world:"earth" },
    estonia: { name:"Estonia", pop:1300, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["russia","latvia"], world:"earth" },
    latvia: { name:"Latvia", pop:1900, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["estonia","russia","lithuania","belarus"], world:"earth" },
    lithuania: { name:"Lithuania", pop:2700, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["latvia","belarus","poland","kaliningrad"], world:"earth" },
    // ASIA
    china: { name:"China", pop:1400000, level:1, owner:"ai", military:10, airports:5, trains:5, adjacent:["russia","mongolia","north_korea","vietnam","laos","myanmar","india","bhutan","nepal","pakistan","afghanistan","tajikistan","kyrgyzstan","kazakhstan"], world:"earth" },
    india: { name:"India", pop:1380000, level:1, owner:"ai", military:10, airports:5, trains:5, adjacent:["pakistan","china","nepal","bhutan","bangladesh","myanmar"], world:"earth" },
    japan: { name:"Japan", pop:125000, level:1, owner:"ai", military:3, airports:3, trains:3, adjacent:[], world:"earth" },
    south_korea: { name:"South Korea", pop:51000, level:1, owner:"ai", military:2, airports:2, trains:2, adjacent:["north_korea"], world:"earth" },
    north_korea: { name:"North Korea", pop:25000, level:1, owner:"ai", military:3, airports:1, trains:1, adjacent:["china","russia","south_korea"], world:"earth" },
    vietnam: { name:"Vietnam", pop:97000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["china","laos","cambodia"], world:"earth" },
    thailand: { name:"Thailand", pop:69000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["myanmar","laos","cambodia","malaysia"], world:"earth" },
    indonesia: { name:"Indonesia", pop:273000, level:1, owner:"ai", military:5, airports:4, trains:3, adjacent:["malaysia","papua_new_guinea","east_timor"], world:"earth" },
    philippines: { name:"Philippines", pop:109000, level:1, owner:"ai", military:2, airports:2, trains:1, adjacent:[], world:"earth" },
    pakistan: { name:"Pakistan", pop:220000, level:1, owner:"ai", military:4, airports:2, trains:2, adjacent:["india","afghanistan","iran","china"], world:"earth" },
    bangladesh: { name:"Bangladesh", pop:164000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["india","myanmar"], world:"earth" },
    iran: { name:"Iran", pop:83000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["turkey","iraq","armenia","azerbaijan","turkmenistan","afghanistan","pakistan"], world:"earth" },
    iraq: { name:"Iraq", pop:40000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["turkey","syria","jordan","saudi_arabia","kuwait","iran"], world:"earth" },
    saudi_arabia: { name:"Saudi Arabia", pop:34000, level:1, owner:"ai", military:3, airports:2, trains:1, adjacent:["jordan","iraq","kuwait","qatar","uae","oman","yemen"], world:"earth" },
    turkey: { name:"Turkey", pop:84000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["bulgaria","greece","georgia","armenia","azerbaijan","iran","iraq","syria"], world:"earth" },
    israel: { name:"Israel", pop:9000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["lebanon","syria","jordan","egypt"], world:"earth" },
    syria: { name:"Syria", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["turkey","iraq","jordan","israel","lebanon"], world:"earth" },
    kazakhstan: { name:"Kazakhstan", pop:19000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["russia","china","kyrgyzstan","uzbekistan","turkmenistan"], world:"earth" },
    mongolia: { name:"Mongolia", pop:3300, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["russia","china"], world:"earth" },
    afghanistan: { name:"Afghanistan", pop:38000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["iran","pakistan","china","tajikistan","uzbekistan","turkmenistan"], world:"earth" },
    // AMERICAS
    usa: { name:"United States", pop:331000, level:1, owner:"ai", military:10, airports:8, trains:8, adjacent:["canada","mexico"], world:"earth" },
    canada: { name:"Canada", pop:38000, level:1, owner:"ai", military:2, airports:3, trains:3, adjacent:["usa"], world:"earth" },
    mexico: { name:"Mexico", pop:128000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["usa","guatemala","belize"], world:"earth" },
    brazil: { name:"Brazil", pop:213000, level:1, owner:"ai", military:4, airports:3, trains:3, adjacent:["venezuela","guyana","suriname","colombia","peru","bolivia","paraguay","argentina","uruguay"], world:"earth" },
    argentina: { name:"Argentina", pop:45000, level:1, owner:"ai", military:2, airports:2, trains:2, adjacent:["chile","bolivia","paraguay","brazil","uruguay"], world:"earth" },
    colombia: { name:"Colombia", pop:50000, level:1, owner:"ai", military:2, airports:2, trains:1, adjacent:["venezuela","brazil","peru","ecuador","panama"], world:"earth" },
    peru: { name:"Peru", pop:33000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["ecuador","colombia","brazil","bolivia","chile"], world:"earth" },
    chile: { name:"Chile", pop:19000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["peru","bolivia","argentina"], world:"earth" },
    venezuela: { name:"Venezuela", pop:28000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["colombia","brazil","guyana"], world:"earth" },
    cuba: { name:"Cuba", pop:11000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:[], world:"earth" },
    // AFRICA
    egypt: { name:"Egypt", pop:100000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["israel","sudan","libya"], world:"earth" },
    nigeria: { name:"Nigeria", pop:206000, level:1, owner:"ai", military:3, airports:2, trains:2, adjacent:["benin","niger","chad","cameroon"], world:"earth" },
    south_africa: { name:"South Africa", pop:59000, level:1, owner:"ai", military:2, airports:2, trains:2, adjacent:["namibia","botswana","zimbabwe","mozambique","eswatini","lesotho"], world:"earth" },
    kenya: { name:"Kenya", pop:53000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["ethiopia","somalia","south_sudan","uganda","tanzania"], world:"earth" },
    ethiopia: { name:"Ethiopia", pop:115000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["eritrea","djibouti","somalia","kenya","south_sudan","sudan"], world:"earth" },
    drc: { name:"DR Congo", pop:89000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["congo","central_african_republic","south_sudan","uganda","rwanda","burundi","tanzania","zambia","angola"], world:"earth" },
    sudan: { name:"Sudan", pop:43000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["egypt","libya","chad","central_african_republic","south_sudan","ethiopia","eritrea"], world:"earth" },
    libya: { name:"Libya", pop:6800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["egypt","sudan","chad","niger","algeria","tunisia"], world:"earth" },
    algeria: { name:"Algeria", pop:44000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["morocco","western_sahara","mauritania","mali","niger","libya","tunisia"], world:"earth" },
    morocco: { name:"Morocco", pop:37000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["algeria","western_sahara"], world:"earth" },
    ghana: { name:"Ghana", pop:31000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["ivory_coast","burkina_faso","togo"], world:"earth" },
    cameroon: { name:"Cameroon", pop:26000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["nigeria","chad","central_african_republic","equatorial_guinea","gabon","congo"], world:"earth" },
    tanzania: { name:"Tanzania", pop:60000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["kenya","uganda","rwanda","burundi","drc","zambia","malawi","mozambique"], world:"earth" },
    angola: { name:"Angola", pop:32000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["drc","zambia","namibia"], world:"earth" },
    madagascar: { name:"Madagascar", pop:28000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:[], world:"earth" },
    // OCEANIA
    australia: { name:"Australia", pop:25000, level:1, owner:"ai", military:2, airports:3, trains:2, adjacent:[], world:"earth" },
    new_zealand: { name:"New Zealand", pop:5000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:[], world:"earth" },
    papua_new_guinea: { name:"Papua New Guinea", pop:9000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["indonesia"], world:"earth" }
};
