export const countries = {
    afghanistan: { name:"Afghanistan", pop:38000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["india","pakistan","china"], world:"earth" },
    algeria: { name:"Algeria", pop:43000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["morocco"], world:"earth" },
    angola: { name:"Angola", pop:32000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["dr_congo"], world:"earth" },
    argentina: { name:"Argentina", pop:45000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bolivia","paraguay","uruguay"], world:"earth" },
    australia: { name:"Australia", pop:25000, level:2, owner:"ai", military:1, airports:2, trains:1, adjacent:["indonesia"], world:"earth" },
    austria: { name:"Austria", pop:9000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["slovakia","poland","hungary","romania","serbia","croatia"], world:"earth" },
    bangladesh: { name:"Bangladesh", pop:164000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["india","china","myanmar"], world:"earth" },
    belgium: { name:"Belgium", pop:11000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","switzerland","italy","germany","austria"], world:"earth" },
    bolivia: { name:"Bolivia", pop:11600, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["paraguay"], world:"earth" },
    brazil: { name:"Brazil", pop:212000, level:2, owner:"ai", military:1, airports:2, trains:1, adjacent:["chile","argentina","france","bolivia","ecuador","paraguay","uruguay"], world:"earth" },
    bulgaria: { name:"Bulgaria", pop:6900, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["greece","serbia","croatia","ukraine","turkey","moldova"], world:"earth" },
    canada: { name:"Canada", pop:38000, level:2, owner:"ai", military:1, airports:3, trains:1, adjacent:["usa","france"], world:"earth" },
    chile: { name:"Chile", pop:19100, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["argentina","bolivia"], world:"earth" },
    china: { name:"China", pop:1440000, level:3, owner:"ai", military:4, airports:3, trains:3, adjacent:["mongolia","north_korea","south_korea","japan","vietnam","thailand","philippines","myanmar","bangladesh"], world:"earth" },
    colombia: { name:"Colombia", pop:50800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["venezuela","peru","brazil","ecuador"], world:"earth" },
    croatia: { name:"Croatia", pop:4100, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["ukraine"], world:"earth" },
    cuba: { name:"Cuba", pop:11300, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["usa","mexico"], world:"earth" },
    czech: { name:"Czechia", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["austria","slovakia","poland","hungary","romania","serbia","croatia","ukraine","lithuania"], world:"earth" },
    denmark: { name:"Denmark", pop:5800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["netherlands","belgium","france","germany","czech","poland"], world:"earth" },
    dr_congo: { name:"D.R. Congo", pop:89000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["angola","sudan"], world:"earth" },
    ecuador: { name:"Ecuador", pop:17600, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["colombia","venezuela","peru","brazil"], world:"earth" },
    egypt: { name:"Egypt", pop:102000, level:2, owner:"ai", military:2, airports:1, trains:1, adjacent:["libya","sudan"], world:"earth" },
    estonia: { name:"Estonia", pop:1300, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["latvia","lithuania"], world:"earth" },
    ethiopia: { name:"Ethiopia", pop:115000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["kenya","dr_congo","sudan"], world:"earth" },
    finland: { name:"Finland", pop:5500, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["estonia","latvia","lithuania"], world:"earth" },
    france: { name:"France", pop:67000, level:2, owner:"ai", military:2, airports:2, trains:2, adjacent:["switzerland","italy","germany","czech","austria","libya","algeria","morocco","nigeria","dr_congo"], world:"earth" },
    germany: { name:"Germany", pop:83000, level:2, owner:"ai", military:1, airports:1, trains:2, adjacent:["czech","austria","slovakia","poland","hungary","serbia","croatia"], world:"earth" },
    greece: { name:"Greece", pop:104000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["serbia","croatia","ukraine","turkey","moldova","egypt","libya"], world:"earth" },
    hungary: { name:"Hungary", pop:9600, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["romania","bulgaria","greece","serbia","croatia","ukraine","turkey","moldova"], world:"earth" },
    india: { name:"India", pop:1400000, level:3, owner:"ai", military:3, airports:2, trains:3, adjacent:["pakistan","china","thailand","indonesia","malaysia","myanmar","bangladesh"], world:"earth" },
    indonesia: { name:"Indonesia", pop:273000, level:2, owner:"ai", military:1, airports:1, trains:1, adjacent:["philippines","malaysia","australia"], world:"earth" },
    iran: { name:"Iran", pop:84000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["iraq","saudi","afghanistan","pakistan"], world:"earth" },
    iraq: { name:"Iraq", pop:40000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["saudi","egypt"], world:"earth" },
    ireland: { name:"Ireland", pop:4900, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["uk","france"], world:"earth" },
    italy: { name:"Italy", pop:60000, level:2, owner:"ai", military:1, airports:1, trains:1, adjacent:["germany","czech","austria","slovakia","poland","hungary","romania","bulgaria","greece","serbia","croatia","ukraine","libya","algeria"], world:"earth" },
    japan: { name:"Japan", pop:126000, level:2, owner:"ai", military:2, airports:2, trains:2, adjacent:["china","north_korea","south_korea"], world:"earth" },
    kazakhstan: { name:"Kazakhstan", pop:18700, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["iran","iraq","afghanistan","pakistan","china","mongolia"], world:"earth" },
    kenya: { name:"Kenya", pop:53000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["dr_congo","sudan"], world:"earth" },
    latvia: { name:"Latvia", pop:1900, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["lithuania"], world:"earth" },
    libya: { name:"Libya", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["algeria","sudan"], world:"earth" },
    lithuania: { name:"Lithuania", pop:2800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["norway","sweden","finland","czech","poland","ukraine","estonia","latvia"], world:"earth" },
    malaysia: { name:"Malaysia", pop:32000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["myanmar"], world:"earth" },
    mexico: { name:"Mexico", pop:128000, level:2, owner:"ai", military:1, airports:1, trains:1, adjacent:["cuba"], world:"earth" },
    moldova: { name:"Moldova", pop:2600, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["poland","hungary","romania","bulgaria","greece","serbia","ukraine","turkey"], world:"earth" },
    mongolia: { name:"Mongolia", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["kazakhstan","china"], world:"earth" },
    morocco: { name:"Morocco", pop:36000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["portugal","spain","france","algeria"], world:"earth" },
    myanmar: { name:"Myanmar", pop:54000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bangladesh"], world:"earth" },
    netherlands: { name:"Netherlands", pop:17000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["belgium","france","switzerland","italy","germany","austria"], world:"earth" },
    new_zealand: { name:"New Zealand", pop:4800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:[], world:"earth" },
    nigeria: { name:"Nigeria", pop:206000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["dr_congo"], world:"earth" },
    north_korea: { name:"N. Korea", pop:10000, level:1, owner:"ai", military:3, airports:1, trains:1, adjacent:["south_korea","japan"], world:"earth" },
    norway: { name:"Norway", pop:14000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["sweden","finland","uk","denmark","germany","poland","estonia","latvia","lithuania"], world:"earth" },
    pakistan: { name:"Pakistan", pop:220000, level:1, owner:"ai", military:3, airports:1, trains:1, adjacent:["china"], world:"earth" },
    paraguay: { name:"Paraguay", pop:7100, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["uruguay"], world:"earth" },
    peru: { name:"Peru", pop:32500, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["brazil","chile","argentina","bolivia","ecuador"], world:"earth" },
    philippines: { name:"Philippines", pop:109000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["malaysia"], world:"earth" },
    poland: { name:"Poland", pop:37000, level:2, owner:"ai", military:1, airports:1, trains:1, adjacent:["hungary","romania","serbia","croatia","ukraine","estonia","latvia","lithuania","moldova"], world:"earth" },
    portugal: { name:"Portugal", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["spain","france","algeria","morocco"], world:"earth" },
    romania: { name:"Romania", pop:19200, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["bulgaria","greece","serbia","croatia","ukraine","turkey","moldova"], world:"earth" },
    saudi: { name:"Saudi Arabia", pop:34800, level:2, owner:"ai", military:2, airports:2, trains:1, adjacent:["egypt","ethiopia","sudan"], world:"earth" },
    serbia: { name:"Serbia", pop:8700, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["croatia","ukraine","turkey","moldova"], world:"earth" },
    slovakia: { name:"Slovakia", pop:5400, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["poland","hungary","romania","bulgaria","serbia","croatia","ukraine"], world:"earth" },
    south_africa: { name:"S. Africa", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:[], world:"earth" },
    south_korea: { name:"S. Korea", pop:10000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["japan"], world:"earth" },
    spain: { name:"Spain", pop:47000, level:2, owner:"ai", military:1, airports:1, trains:1, adjacent:["france","switzerland","italy","germany","algeria","morocco"], world:"earth" },
    sudan: { name:"Sudan", pop:43800, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["saudi","egypt","libya","ethiopia","kenya","dr_congo"], world:"earth" },
    sweden: { name:"Sweden", pop:10000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["finland","denmark","netherlands","germany","poland","ukraine","estonia","latvia","lithuania"], world:"earth" },
    switzerland: { name:"Switzerland", pop:8000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["italy","germany","czech","austria","poland","croatia"], world:"earth" },
    thailand: { name:"Thailand", pop:70000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["indonesia","malaysia","myanmar"], world:"earth" },
    turkey: { name:"Turkey", pop:84000, level:2, owner:"ai", military:3, airports:2, trains:1, adjacent:["moldova","kazakhstan","iran","iraq","saudi","libya"], world:"earth" },
    uk: { name:"U.K.", pop:67000, level:2, owner:"ai", military:2, airports:2, trains:1, adjacent:["netherlands","belgium","france"], world:"earth" },
    ukraine: { name:"Ukraine", pop:44000, level:1, owner:"ai", military:2, airports:1, trains:1, adjacent:["turkey","latvia","lithuania","moldova"], world:"earth" },
    uruguay: { name:"Uruguay", pop:3450, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["brazil","argentina","paraguay"], world:"earth" },
    usa: { name:"United States", pop:331000, level:3, owner:"ai", military:4, airports:3, trains:1, adjacent:["mexico","cuba"], world:"earth" },
    venezuela: { name:"Venezuela", pop:28400, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["peru","brazil","ecuador"], world:"earth" },
    vietnam: { name:"Vietnam", pop:97000, level:1, owner:"ai", military:1, airports:1, trains:1, adjacent:["thailand","indonesia","malaysia","myanmar"], world:"earth" },
};
