export const marsCountries = {
    acidalia_planitia: { name:"Acidalia Planitia", pop:0, level:1, owner:"ai", military:1, airports:1, trains:0, adjacent:[utydor_planitia,north_polar_cap], world:"mars" },
    albor_tholus: { name:"Albor Tholus", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[elysium_planitia,utopia_planitia,borealis_plain,vastitas_borealis_w,arcadia_planitia], world:"mars" },
    aonia: { name:"Aonia", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[coronae], world:"mars" },
    arcadia_planitia: { name:"Arcadia Planitia", pop:0, level:1, owner:"ai", military:1, airports:1, trains:0, adjacent:[albor_tholus,elysium_planitia,utopia_planitia], world:"mars" },
    argyre_basin: { name:"Argyre Basin", pop:0, level:1, owner:"ai", military:1, airports:1, trains:0, adjacent:[aonia,thaumasia], world:"mars" },
    arsia_mons: { name:"Arsia Mons", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[pavonis_mons,tharsis_ridge], world:"mars" },
    ascraeus_mons: { name:"Ascraeus Mons", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[tharsis_ridge], world:"mars" },
    australis: { name:"Australis S", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[south_polar_cap,mare_south], world:"mars" },
    australis_south: { name:"Australis Far", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[south_polar_cap], world:"mars" },
    borealis_plain: { name:"Borealis Plain", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[vastitas_borealis_w,diacria], world:"mars" },
    capri_chaos: { name:"Capri Chaos", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[eos_chasma], world:"mars" },
    chaos_region: { name:"Chaos Region", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[capri_chaos], world:"mars" },
    chryse_planitia: { name:"Chryse Planitia", pop:0, level:1, owner:"ai", military:1, airports:1, trains:0, adjacent:[lunae_palus], world:"mars" },
    coronae: { name:"Coronae", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[aonia,solis_planum], world:"mars" },
    diacria: { name:"Diacria", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[elysium_mons,hecates_tholus,north_polar_cap,borealis_plain], world:"mars" },
    elysium_mons: { name:"Elysium Mons", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[hecates_tholus,albor_tholus,elysium_planitia,borealis_plain,vastitas_borealis_w,diacria], world:"mars" },
    elysium_planitia: { name:"Elysium Planitia", pop:0, level:1, owner:"ai", military:1, airports:1, trains:0, adjacent:[borealis_plain,arcadia_planitia], world:"mars" },
    eos_chasma: { name:"Eos Chasma", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[capri_chaos], world:"mars" },
    hadriacus: { name:"Hadriacus", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[promethei,hellas_outlier], world:"mars" },
    hecates_tholus: { name:"Hecates Tholus", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[north_polar_cap,borealis_plain,diacria], world:"mars" },
    hellas_basin: { name:"Hellas Basin", pop:0, level:2, owner:"ai", military:2, airports:1, trains:0, adjacent:[hellespontus,hadriacus,promethei], world:"mars" },
    hellas_outlier: { name:"Hellas Outlier", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[hadriacus], world:"mars" },
    hellespontus: { name:"Hellespontus", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[tyrrhenus], world:"mars" },
    isidis_planitia: { name:"Isidis Planitia", pop:0, level:1, owner:"ai", military:1, airports:1, trains:0, adjacent:[elysium_planitia], world:"mars" },
    lunae_palus: { name:"Lunae Palus", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[acidalia_planitia], world:"mars" },
    mare_south: { name:"Mare S", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[noachis,australis], world:"mars" },
    marineris_valles: { name:"Valles Marineris", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[chryse_planitia], world:"mars" },
    noachis: { name:"Noachis", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[australis,mare_south], world:"mars" },
    north_polar_cap: { name:"N. Polar Cap", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[diacria], world:"mars" },
    olympus_mons: { name:"Olympus Mons", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[arsia_mons,pavonis_mons,ascraeus_mons,tharsis_ridge], world:"mars" },
    pavonis_mons: { name:"Pavonis Mons", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[ascraeus_mons,tharsis_ridge], world:"mars" },
    promethei: { name:"Promethei", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[hellas_basin,hadriacus], world:"mars" },
    solis_planum: { name:"Solis Planum", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[coronae], world:"mars" },
    south_polar_cap: { name:"S. Polar Cap", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[australis_south], world:"mars" },
    tharsis_ridge: { name:"Tharsis Ridge", pop:0, level:2, owner:"ai", military:2, airports:1, trains:0, adjacent:[olympus_mons,arsia_mons,pavonis_mons,ascraeus_mons], world:"mars" },
    thaumasia: { name:"Thaumasia", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[noachis], world:"mars" },
    tyrrhenus: { name:"Tyrrhenus", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[solis_planum], world:"mars" },
    utopia_planitia: { name:"Utopia Planitia", pop:0, level:1, owner:"ai", military:2, airports:1, trains:0, adjacent:[borealis_plain,vastitas_borealis_w,arcadia_planitia], world:"mars" },
    utydor_planitia: { name:"Utopia Planitia E", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[isidis_planitia,north_polar_cap], world:"mars" },
    valles_marineris_east: { name:"VM East", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[chaos_region], world:"mars" },
    vastitas_borealis_e: { name:"Vastitas B E", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[], world:"mars" },
    vastitas_borealis_w: { name:"Vastitas B W", pop:0, level:1, owner:"ai", military:1, airports:0, trains:0, adjacent:[elysium_mons,albor_tholus,utopia_planitia,borealis_plain], world:"mars" },
};
