export const marsCountries = {
    olympus_imperium: { name:"Olympus Imperium", pop:50000, level:5, owner:"ai", military:8, airports:5, trains:4, adjacent:["tharsis_dominion","elysium_collective","vallis_marineris"], world:"mars" },
    tharsis_dominion: { name:"Tharsis Dominion", pop:45000, level:5, owner:"ai", military:7, airports:4, trains:4, adjacent:["olympus_imperium","noctis_labyrinth","arcadia_plains"], world:"mars" },
    elysium_collective: { name:"Elysium Collective", pop:42000, level:4, owner:"ai", military:6, airports:4, trains:3, adjacent:["olympus_imperium","utopia_basin","amazonis_planitia"], world:"mars" },
    vallis_marineris: { name:"Vallis Marineris", pop:48000, level:5, owner:"ai", military:9, airports:5, trains:5, adjacent:["olympus_imperium","noctis_labyrinth","candor_chasma","melas_chasma"], world:"mars" },
    noctis_labyrinth: { name:"Noctis Labyrinth", pop:35000, level:4, owner:"ai", military:5, airports:3, trains:3, adjacent:["tharsis_dominion","vallis_marineris","sinai_planum"], world:"mars" },
    arcadia_plains: { name:"Arcadia Plains", pop:38000, level:4, owner:"ai", military:5, airports:3, trains:3, adjacent:["tharsis_dominion","tempe_terra","alba_patera"], world:"mars" },
    utopia_basin: { name:"Utopia Basin", pop:40000, level:4, owner:"ai", military:6, airports:3, trains:3, adjacent:["elysium_collective","isidis_planitia","nepenthes_mensae"], world:"mars" },
    amazonis_planitia: { name:"Amazonis Planitia", pop:36000, level:4, owner:"ai", military:5, airports:3, trains:2, adjacent:["elysium_collective","lunae_planum","daedalia_planum"], world:"mars" },
    candor_chasma: { name:"Candor Chasma", pop:32000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["vallis_marineris","melas_chasma","ophir_chasma"], world:"mars" },
    melas_chasma: { name:"Melas Chasma", pop:34000, level:3, owner:"ai", military:5, airports:2, trains:2, adjacent:["vallis_marineris","candor_chasma","coprates_chasma"], world:"mars" },
    ophir_chasma: { name:"Ophir Chasma", pop:30000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["candor_chasma","sinai_planum","juventae_chasma"], world:"mars" },
    coprates_chasma: { name:"Coprates Chasma", pop:31000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["melas_chasma","capri_chasma","aurorae_chaos"], world:"mars" },
    sinai_planum: { name:"Sinai Planum", pop:33000, level:3, owner:"ai", military:5, airports:2, trains:2, adjacent:["noctis_labyrinth","ophir_chasma","solis_planum"], world:"mars" },
    solis_planum: { name:"Solis Planum", pop:35000, level:4, owner:"ai", military:5, airports:3, trains:3, adjacent:["sinai_planum","lunae_planum","daedalia_planum"], world:"mars" },
    lunae_planum: { name:"Lunae Planum", pop:32000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["amazonis_planitia","solis_planum","tempe_terra"], world:"mars" },
    daedalia_planum: { name:"Daedalia Planum", pop:28000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["amazonis_planitia","solis_planum","phaethontis"], world:"mars" },
    tempe_terra: { name:"Tempe Terra", pop:30000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["arcadia_plains","lunae_planum","alba_patera"], world:"mars" },
    alba_patera: { name:"Alba Patera", pop:27000, level:3, owner:"ai", military:3, airports:2, trains:2, adjacent:["arcadia_plains","tempe_terra","tharsis_tholus"], world:"mars" },
    isidis_planitia: { name:"Isidis Planitia", pop:29000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["utopia_basin","nepenthes_mensae","tyrrhena_terra"], world:"mars" },
    nepenthes_mensae: { name:"Nepenthes Mensae", pop:26000, level:3, owner:"ai", military:3, airports:2, trains:1, adjacent:["utopia_basin","isidis_planitia","aeolis_dorsa"], world:"mars" },
    tyrrhena_terra: { name:"Tyrrhena Terra", pop:31000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["isidis_planitia","hellas_basin","hesperia_planum"], world:"mars" },
    hellas_basin: { name:"Hellas Basin", pop:45000, level:5, owner:"ai", military:7, airports:4, trains:4, adjacent:["tyrrhena_terra","hesperia_planum","promethei_terra"], world:"mars" },
    hesperia_planum: { name:"Hesperia Planum", pop:33000, level:4, owner:"ai", military:5, airports:3, trains:3, adjacent:["tyrrhena_terra","hellas_basin","malea_planum"], world:"mars" },
    promethei_terra: { name:"Promethei Terra", pop:28000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["hellas_basin","malea_planum","australe_planum"], world:"mars" },
    malea_planum: { name:"Malea Planum", pop:25000, level:3, owner:"ai", military:3, airports:2, trains:1, adjacent:["hesperia_planum","promethei_terra"], world:"mars" },
    australe_planum: { name:"Australe Planum", pop:22000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["promethei_terra","sirenum_terra"], world:"mars" },
    sirenum_terra: { name:"Sirenum Terra", pop:24000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["australe_planum","phaethontis","cimmeria_terra"], world:"mars" },
    phaethontis: { name:"Phaethontis", pop:26000, level:3, owner:"ai", military:3, airports:2, trains:1, adjacent:["daedalia_planum","sirenum_terra","aonia_terra"], world:"mars" },
    aonia_terra: { name:"Aonia Terra", pop:23000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["phaethontis","cimmeria_terra"], world:"mars" },
    cimmeria_terra: { name:"Cimmeria Terra", pop:27000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["sirenum_terra","aonia_terra","aeolis_dorsa"], world:"mars" },
    aeolis_dorsa: { name:"Aeolis Dorsa", pop:29000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["nepenthes_mensae","cimmeria_terra","elysium_mons"], world:"mars" },
    elysium_mons: { name:"Elysium Mons", pop:38000, level:4, owner:"ai", military:6, airports:3, trains:3, adjacent:["aeolis_dorsa","elysium_collective"], world:"mars" },
    tharsis_tholus: { name:"Tharsis Tholus", pop:25000, level:3, owner:"ai", military:3, airports:2, trains:1, adjacent:["alba_patera","ascraeus_mons"], world:"mars" },
    ascraeus_mons: { name:"Ascraeus Mons", pop:35000, level:4, owner:"ai", military:5, airports:3, trains:3, adjacent:["tharsis_tholus","pavonis_mons"], world:"mars" },
    pavonis_mons: { name:"Pavonis Mons", pop:36000, level:4, owner:"ai", military:5, airports:3, trains:3, adjacent:["ascraeus_mons","arsia_mons"], world:"mars" },
    arsia_mons: { name:"Arsia Mons", pop:34000, level:4, owner:"ai", military:5, airports:3, trains:2, adjacent:["pavonis_mons","solis_planum"], world:"mars" },
    capri_chasma: { name:"Capri Chasma", pop:24000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["coprates_chasma","aurorae_chaos"], world:"mars" },
    aurorae_chaos: { name:"Aurorae Chaos", pop:22000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["coprates_chasma","capri_chasma"], world:"mars" },
    juventae_chasma: { name:"Juventae Chasma", pop:26000, level:3, owner:"ai", military:3, airports:2, trains:1, adjacent:["ophir_chasma","xanthe_terra"], world:"mars" },
    xanthe_terra: { name:"Xanthe Terra", pop:28000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["juventae_chasma","chryse_planitia"], world:"mars" },
    chryse_planitia: { name:"Chryse Planitia", pop:30000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["xanthe_terra","acidalia_planitia"], world:"mars" },
    acidalia_planitia: { name:"Acidalia Planitia", pop:32000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["chryse_planitia","arcadia_plains"], world:"mars" },
    new_marineris: { name:"New Marineris", pop:40000, level:4, owner:"ai", military:6, airports:3, trains:3, adjacent:["vallis_marineris","coprates_chasma"], world:"mars" },
    olympus_outpost: { name:"Olympus Outpost", pop:42000, level:4, owner:"ai", military:6, airports:3, trains:3, adjacent:["olympus_imperium","tharsis_dominion"], world:"mars" },
    red_tharsis: { name:"Red Tharsis", pop:38000, level:4, owner:"ai", military:5, airports:3, trains:2, adjacent:["tharsis_dominion","pavonis_mons"], world:"mars" },
    hellas_rim: { name:"Hellas Rim", pop:32000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["hellas_basin","promethei_terra"], world:"mars" },
    polar_cap_north: { name:"Polar Cap North", pop:20000, level:2, owner:"ai", military:3, airports:1, trains:1, adjacent:["arcadia_plains","alba_patera"], world:"mars" },
    polar_cap_south: { name:"Polar Cap South", pop:18000, level:2, owner:"ai", military:2, airports:1, trains:1, adjacent:["australe_planum"], world:"mars" },
    gale_crater: { name:"Gale Crater", pop:28000, level:3, owner:"ai", military:4, airports:2, trains:2, adjacent:["aeolis_dorsa","elysium_mons"], world:"mars" },
    spirit_plains: { name:"Spirit Plains", pop:25000, level:3, owner:"ai", military:3, airports:2, trains:1, adjacent:["gale_crater","tyrrhena_terra"], world:"mars" }
};
